apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:latest
        ports:
        - containerPort: 8000
        # Define una persistencia de datos (Volumes) si necesitas que los datos
        # no se pierdan al reiniciar el pod. Esto es crucial en Kyma.
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP